baseURL = 'https://vladromanov.com/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'
ignoreErrors: ["error-remote-getjson"]  #yml or ignoreErrors = ["error-remote-getjson"]  #toml
